🎨 💄 Modify component name, fix props type, ui
X-y-game/x-y-game pull request #35
Opened 2022-02-18 18:48 UTC by whara123

1. 명시적이지 않던 컴포넌트 이름을 변경
2. modal props 오류를 일부 수정
3. 룸/채널 화면 색상이 꽉 차도록 변경

2022-02-19 09:59 UTC, Luceta requested changes

2022-02-19 09:59 UTC, Luceta commented on src/components/Modal/index.js
> +      {!isFinishResult ? (
👀

2022-02-21 04:08 UTC, jiseung-kang approved these changes
고생많으셨어요~!~!

2022-02-21 04:08 UTC, jiseung-kang commented on src/components/Modal/index.js
> +      {!isFinishResult ? (
isFinishedResult !!

2022-02-21 05:59 UTC, Luceta approved these changes

2022-02-21 05:59 UTC, merged